/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
/**
 *
 * @author dell pc
 */
public class SearchPage extends javax.swing.JFrame implements WindowListener{
    Connection con;
    Statement stmt;
    String username;
    ResultSet rs;
    JFrame frame;
    JTable jt;
    JScrollPane sp;
    String header[]={"ID","Name","Mobile no.","Email","Gender","DOB","Age","Address","DOA","Java","DS","AOA","Python","Fees","Advance","Payment Method","Cheque no.","Bank","Balance Fees"};
    String search[][]=new String[100][19];
    /**
     * Creates new form SearchPage
     */
    public SearchPage(Connection con,Statement stmt,String username){
        this.con=con;
        this.stmt=stmt;
        this.username=username;
        initComponents();
        setIconImage(new ImageIcon("FMS.png").getImage());
        addWindowListener(this);
        setVisible(true);
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Search Page");
        setLocation(new java.awt.Point(400, 50));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setBackground(new java.awt.Color(0, 51, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setText("Student ID");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setText("Student Mobile no.");

        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 51, 255));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 51, 255));
        jButton3.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Show All Students");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new HomePage(username,con,stmt); 
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean flag=true;
        try{
            if(jTextField1.getText().isEmpty())
                rs=stmt.executeQuery("SELECT * FROM StudentData WHERE `Mobile no.`='"+jTextField2.getText()+"'");
            else if(jTextField2.getText().isEmpty())
                rs=stmt.executeQuery("SELECT * FROM StudentData WHERE ID='"+jTextField1.getText()+"'");
            else if(!(jTextField1.getText().isEmpty()&&jTextField2.getText().isEmpty()))
                rs=stmt.executeQuery("SELECT * FROM StudentData WHERE ID='"+jTextField1.getText()+"' AND `Mobile no.`='"+jTextField2.getText()+"'");
            if(!rs.next()){
                JOptionPane.showMessageDialog(null,"No Such Record!","Search Page",JOptionPane.WARNING_MESSAGE);
                flag=false;
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error Finding Record!","Search Page",JOptionPane.WARNING_MESSAGE);
            flag=false;
        }
        if(flag){
            frame=new JFrame("Student");
            frame.setVisible(true);
            frame.setIconImage(new ImageIcon("Screenshot 2025-06-24 195725.png").getImage());
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            try{
                do{
                    search[0][0]=rs.getString(1);
                    search[0][1]=rs.getString(2);
                    search[0][2]=rs.getString(3);
                    search[0][3]=rs.getString(4);
                    search[0][4]=rs.getString(5);
                    search[0][5]=rs.getString(6);
                    search[0][6]=rs.getString(7);
                    search[0][7]=rs.getString(8);
                    search[0][8]=rs.getString(9);
                    search[0][9]=rs.getString(10);
                    search[0][10]=rs.getString(11);
                    search[0][11]=rs.getString(12);
                    search[0][12]=rs.getString(13);
                    search[0][13]=rs.getString(14);
                    search[0][14]=rs.getString(15);
                    search[0][15]=rs.getString(16);
                    search[0][16]=rs.getString(17);
                    search[0][17]=rs.getString(18);
                    search[0][18]=rs.getString(19);
                }
                while(rs.next());
                jt=new JTable(search,header);
                sp=new JScrollPane(jt);
                frame.add(sp);
                frame.pack();
                jTextField1.setText("");
                jTextField2.setText("");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Error finding records\nTry Again!","Search Page",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean flag=true;
        int i=0;
        try{
            rs=stmt.executeQuery("SELECT * FROM StudentData");
            if(!rs.next()){
                JOptionPane.showMessageDialog(null,"No Records!","Search Page",JOptionPane.WARNING_MESSAGE);
                flag=false;
            }
            if(flag){
                frame=new JFrame("Student");
                frame.setVisible(true);
                frame.setIconImage(new ImageIcon("Screenshot 2025-06-24 195725.png").getImage());
                frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                do{
                    search[i][0]=rs.getString(1);
                    search[i][1]=rs.getString(2);
                    search[i][2]=rs.getString(3);
                    search[i][3]=rs.getString(4);
                    search[i][4]=rs.getString(5);
                    search[i][5]=rs.getString(6);
                    search[i][6]=rs.getString(7);
                    search[i][7]=rs.getString(8);
                    search[i][8]=rs.getString(9);
                    search[i][9]=rs.getString(10);
                    search[i][10]=rs.getString(11);
                    search[i][11]=rs.getString(12);
                    search[i][12]=rs.getString(13);
                    search[i][13]=rs.getString(14);
                    search[i][14]=rs.getString(15);
                    search[i][15]=rs.getString(16);
                    search[i][16]=rs.getString(17);
                    search[i][17]=rs.getString(18);
                    search[i][18]=rs.getString(19);
                    i++;
                }
                while(rs.next());
                jt=new JTable(search,header);
                sp=new JScrollPane(jt);
                frame.add(sp);
                frame.pack();
                jTextField1.setText("");
                jTextField2.setText("");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error finding records\nTry Again!","Search Page",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    @Override
    public void windowClosing(WindowEvent e) {
        new HomePage(username,con,stmt);
        dispose();
    }
    @Override
    public void windowOpened(WindowEvent e) {}
    @Override
    public void windowClosed(WindowEvent e) {}
    @Override
    public void windowIconified(WindowEvent e) {}
    @Override
    public void windowDeiconified(WindowEvent e) {}
    @Override
    public void windowActivated(WindowEvent e) {}
    @Override
    public void windowDeactivated(WindowEvent e) {}
}